- name: Copy Calico manifest
  copy:
    src: "{{ playbook_dir }}/../files/k8s/calico.yaml"
    dest: /tmp/calico.yaml
  delegate_to: "{{ groups['role_k8s_master'][0] }}"
  run_once: true

- name: Install Calico
  command: kubectl apply -f /tmp/calico.yaml
  delegate_to: "{{ groups['role_k8s_master'][0] }}"
  run_once: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf